//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perfilCurricularDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class curriculo
    {
        public curriculo()
        {
            this.experiencia = new HashSet<experiencia>();
            this.formacao = new HashSet<formacao>();
            this.interesse = new HashSet<interesse>();
            this.lingua = new HashSet<lingua>();
            this.proficiencia = new HashSet<proficiencia>();
            this.projeto = new HashSet<projeto>();
            this.telefone = new HashSet<telefone>();
        }
    
        public int id { get; set; }
        public string nomeCompleto { get; set; }
        public string email { get; set; }
        public string profissao { get; set; }
        public string perfilCarreira { get; set; }
        public string linkedinDisplay { get; set; }
        public string linkedin { get; set; }
        public string introProjeto { get; set; }
        public string foto { get; set; }
        public int Login { get; set; }
    
        public virtual login login1 { get; set; }
        public virtual ICollection<experiencia> experiencia { get; set; }
        public virtual ICollection<formacao> formacao { get; set; }
        public virtual ICollection<interesse> interesse { get; set; }
        public virtual ICollection<lingua> lingua { get; set; }
        public virtual ICollection<proficiencia> proficiencia { get; set; }
        public virtual ICollection<projeto> projeto { get; set; }
        public virtual ICollection<telefone> telefone { get; set; }
    }
}
