//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perfilCurricularDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class nivel
    {
        public nivel()
        {
            this.lingua = new HashSet<lingua>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<lingua> lingua { get; set; }
    }
}
