//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perfilCurricularDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public login()
        {
            this.curriculo = new HashSet<curriculo>();
        }
    
        public int id { get; set; }
        public string usuario { get; set; }
        public string senha { get; set; }
        public bool alteracao { get; set; }
    
        public virtual ICollection<curriculo> curriculo { get; set; }
    }
}
