//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perfilCurricularDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class perfilCurricularContext : DbContext
    {
        public perfilCurricularContext()
            : base("name=perfilCurricularContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<experiencia> experiencia { get; set; }
        public virtual DbSet<projeto> projeto { get; set; }
        public virtual DbSet<proficiencia> proficiencia { get; set; }
        public virtual DbSet<telefone> telefone { get; set; }
        public virtual DbSet<formacao> formacao { get; set; }
        public virtual DbSet<lingua> lingua { get; set; }
        public virtual DbSet<nivel> nivel { get; set; }
        public virtual DbSet<interesse> interesse { get; set; }
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<curriculo> curriculo { get; set; }
    }
}
